version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt install -y httpd
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build complete, preparing for deployment..."
artifacts:
  files:
    - '**/*'
